### ISSUE TITLE
Pflichtenheft überarbeiten

### ISSUE THREAD

**Issue by MarcelGamesHD** [MarcelGamesHD/Snake#17]

**Comment by MarcelGamesHD** [comment]
Pflichtenheft wurde als Team überarbeitet.

**Comment by MarcelGamesHD** [comment]
Pflichtenheft wird von Marlene gegengelesen.

**Comment by das-kleine-marlenchen** [comment]
[Pflichtenheft_Snake_1.5.pdf](https://github.com/MarcelGamesHD/Snake/files/10329391/Pflichtenheft_Snake_1.5.pdf)
